name: Prepare Dev Branch
description: Following a release, prepare the dev branch for development on the next release.

inputs:
  release_branch:
    required: false
    default: "release"
    description: "The name of the release branch"
  development_branch:
    required: false
    default: "main"
    description: "The name of the development branch"
  git_author_email:
    required: false
    default: "bot@getpantheon.com"
    description: "Git author email for commits"
  git_author_name:
    required: false
    default: "Pantheon Automation"
    description: "Git author name for commits"
  readme_md:
    required: false
    default: "README.md"
    description: "The readme file to parse for version information"

runs:
  using: "composite"
  steps:
    - name: Update Development Branch
      shell: bash
      env:
        RELEASE_BRANCH: ${{ inputs.release_branch }}
        DEVELOPMENT_BRANCH: ${{ inputs.development_branch }}
        GIT_AUTHOR_EMAIL: ${{ inputs.git_author_email }}
        GIT_AUTHOR_NAME: ${{ inputs.git_author_name }}
      run: bash ${{ github.action_path }}/prepare-dev.sh ${{ inputs.readme_md }}