name: Build, Tag, and Release
description: Build the assets and push them to a new tag. Create a release based on the tag.

inputs:
  draft:
    description: "Create a draft release instead of a regular release."
    required: false
    default: "true"
  build_node_assets:
    description: "Build the node assets."
    required: false
    default: "false"
  build_composer_assets:
    description: "Build the composer assets."
    required: false
    default: "false"
  gh_token:
    description: "The GitHub token to use for authentication."
    required: true
  git_username:
    description: "The username to use for git commits."
    required: false
    default: "Pantheon Automation"
  git_email:
    description: "The email to use for git commits."
    required: false
    default: "bot@getpantheon.com"
  readme_md:
    description: "The readme file name"
    required: false
    default: README.md
  generate_release_notes:
    description: "Use GitHub's generated release notes"
    required: false
    default: false
  prerelease:
    description: "Create a prerelease instead of a regular release."
    required: false
    default: "false"
  main_plugin_file:
    description: "The main plugin file to use for prerelease edits."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      if: ${{ inputs.build_node_assets == 'true' }}
      with:
        node-version: "lts/*"
        cache: "npm"
    - name: Build Node Assets
      if: ${{ inputs.build_node_assets == 'true' }}
      shell: bash
      run: |
        npm ci
        npm run build

    - name: Build Composer Assets
      if: ${{ inputs.build_composer_assets == 'true' }}
      shell: bash
      run: |
        composer install --no-dev -o

    - name: Setup
      shell: bash
      run: |
        README="${{ inputs.readme_md }}"
        # Make sure a README exists.
        if [[ ! -f "$README" ]]; then
          echo "No README file found with the name $README. Set the readme_md value if your file is named differently."
          exit 1
        fi
        VERSION=$(cat "$README"| grep 'Stable tag:' | awk '{print $3}')
        [[ "$VERSION" != "" ]] || exit 1
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Add prerelease details
      if: ${{ inputs.prerelease == 'true' }}
      shell: bash
      run: |
        if [[ -z "${{ inputs.main_plugin_file }}" ]]; then
          echo "No main plugin file specified for prerelease edits."
          exit 0
        fi
        [[ "$VERSION" != "" ]] || exit 0
        OLD_VERSION="$VERSION"
        NEW_VERSION="${VERSION}-${GITHUB_SHA::7}"
        source ${{ github.action_path }}/../src/functions.sh
        process_file "${{ inputs.main_plugin_file }}" "$OLD_VERSION" "$NEW_VERSION"
        git add "${{ inputs.main_plugin_file }}"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit Assets
      shell: bash
      if: ${{ inputs.build_node_assets == 'true' || inputs.build_composer_assets == 'true' }}
      run: |
        [[ "$VERSION" != "" ]] || exit 1
        git config user.name "${{ inputs.git_username }}"
        git config user.email "${{ inputs.git_email }}"
        git checkout -b "robot-release-$VERSION"
        [[ ${{ inputs.build_node_assets }} == "true" ]] && git add -f assets/*
        [[ ${{ inputs.build_composer_assets }} == "true" ]] && git add -f vendor/*
        git commit -m "Release $VERSION"


    - name: Tag
      shell: bash
      run: |
        echo "Releasing version $VERSION ..."
        [[ "$VERSION" != "" ]] || exit 1
        git tag "$VERSION"
        git push origin "$VERSION"
        sleep 1 # if we generate too quickly on the next step tag may not exist.

    # TODO(pwt): Allow pointing this to a file other than readme.md while using readme for canonical version.
    - name: Release with Readme Release Notes
      if: ${{ inputs.generate_release_notes == 'false' }}
      shell: bash
      run: |
        node ${{ github.action_path }}/../scripts/get_release_notes.js ./${{ inputs.readme_md }} >> ./release_notes.md
        gh release create $VERSION --title "$VERSION" -F ./release_notes.md $([[ ${{ inputs.draft }} == "true" ]] && echo "--draft")  $([[ ${{ inputs.prerelease }} == "true" ]] && echo "--prerelease")
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Release with Generated Release Notes
      if: ${{ inputs.generate_release_notes == 'true' }}
      shell: bash
      run: |
        gh release create $VERSION --title "$VERSION" --generate-notes --verify-tag $([[ ${{ inputs.draft }} == "true" ]] && echo "--draft") $([[ ${{ inputs.prerelease }} == "true" ]] && echo "--prerelease")
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
